# Generated by Django 6.0.3 on 2026-04-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cosmetic_condition',
        ),
        migrations.RemoveField(
            model_name='item',
            name='has_original_box',
        ),
        migrations.RemoveField(
            model_name='item',
            name='has_receipt',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_fully_functional',
        ),
        migrations.AlterField(
            model_name='item',
            name='calculated_grade',
            field=models.CharField(choices=[('A', 'Grade A - Like New'), ('B', 'Grade B - Lightly Used'), ('C', 'Grade C - Well Used'), ('D', 'Grade D - Heavily Used')], max_length=1),
        ),
    ]
