# Generated by Django 6.0.3 on 2026-05-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_dents_cracks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='has_original_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='has_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='has_scratches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_fully_functional',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='calculated_grade',
            field=models.CharField(blank=True, choices=[('A', 'Grade A - Like New'), ('B', 'Grade B - Lightly Used'), ('C', 'Grade C - Well Used'), ('D', 'Grade D - Heavily Used')], db_index=True, max_length=1),
        ),
    ]
