# Generated by Django 6.0.3 on 2026-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scamreport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AddField(
            model_name='item',
            name='eco_impact',
            field=models.FloatField(default=0.0, help_text='CO2 saved in kg'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='reason',
            field=models.TextField(),
        ),
    ]
