# Generated by Django 6.0.3 on 2026-06-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_transaction_payment_qr_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qrs/'),
        ),
    ]
