# Generated by Django 6.0.3 on 2026-06-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_profile_payment_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
