# Generated by Django 6.0.3 on 2026-06-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_wallettransaction_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='stripe_payment_intent_id',
        ),
    ]
