# Generated by Django 6.0.6 on 2026-06-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_wallettransaction_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe Payment'), ('WALLET', 'MyPreLove Cash Wallet'), ('DIRECT_QR', 'Direct QR Transfer')], default='STRIPE', max_length=20),
        ),
    ]
