# Generated by Django 6.0.6 on 2026-06-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wallet_balance',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe Payment'), ('DIRECT_QR', 'Direct QR Transfer')], default='STRIPE', max_length=20),
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
