# Generated by Django 6.0.6 on 2026-07-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_profile_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recovery_keywords',
            field=models.JSONField(default=list, blank=True),
        ),
    ]
