# Generated by Django 6.0.6 on 2026-07-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_profile_recovery_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='payment_qr',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_qr_image',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe Payment')], default='STRIPE', max_length=20),
        ),
    ]
