import { StyleSheet, Platform, Dimensions } from 'react-native';
import { COLORS } from '../../../utils/constants';
export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  scrollContent: { paddingBottom: 120 },
  imageContainer: { height: 400, width: '100%' },
  image: { width: '100%', height: '100%', resizeMode: 'cover' },
  placeholderImage: { width: '100%', height: '100%', backgroundColor: COLORS.lightGray, justifyContent: 'center', alignItems: 'center' },
  carouselImage: { width: Dimensions.get('window').width, height: 400, resizeMode: 'cover' },
  paginationDotsContainer: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    marginHorizontal: 4
  },
  activePaginationDot: {
    width: 20,
    backgroundColor: '#FFFFFF'
  },
  topControls: {
    position: 'absolute',
    top: 50,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    zIndex: 10,
  },
  rightControls: { flexDirection: 'row' },
  iconButton: { backgroundColor: 'white', padding: 10, borderRadius: 25, elevation: 5, marginLeft: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  infoSection: { padding: 20, marginTop: -20, backgroundColor: COLORS.background, borderTopLeftRadius: 25, borderTopRightRadius: 25 },
  titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginTop: 10 },
  title: {
    fontSize: 28,
    fontWeight: '600',
    color: COLORS.black,
    flex: 1,
    letterSpacing: -0.5,
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif'
  },
  negotiableBadgeDetail: {
    backgroundColor: COLORS.eco,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    marginLeft: 10,
  },
  negotiableTextDetail: {
    fontSize: 12,
    fontWeight: 'bold',
    color: COLORS.success,
  },
  priceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
  price: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.primary,
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif'
  },
  gradeBadgeContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.lightGray, padding: 4, borderRadius: 10 },
  infoIcon: { marginLeft: 8 },
  ecoBanner: {
    backgroundColor: COLORS.eco,
    padding: 18,
    borderRadius: 16,
    marginTop: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1
  },
  ecoHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  ecoTitle: { fontSize: 16, fontWeight: 'bold', color: COLORS.ecoText, marginLeft: 8 },
  ecoText: { fontSize: 14, color: COLORS.ecoText, lineHeight: 20 },
  sellerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2
  },
  sellerAvatar: { width: 56, height: 56, borderRadius: 28, backgroundColor: COLORS.primary, justifyContent: 'center', alignItems: 'center' },
  avatarText: { color: COLORS.white, fontSize: 22, fontWeight: 'bold' },
  verifiedBadge: { position: 'absolute', bottom: -2, right: -2, backgroundColor: 'white', borderRadius: 12, elevation: 2 },
  sellerInfo: { flex: 1, marginLeft: 16 },
  sellerName: { fontSize: 18, fontWeight: 'bold', color: COLORS.black },
  sellerTagRow: { flexDirection: 'row', alignItems: 'center', marginTop: 2 },
  sellerTagIcon: { marginRight: 4 },
  sellerTag: { fontSize: 13, color: COLORS.gray },
  trustScoreContainer: { alignItems: 'flex-end' },
  trustScore: { fontSize: 16, fontWeight: 'bold', color: COLORS.primary },
  salesCount: { fontSize: 13, color: COLORS.gray, marginTop: 2 },
  sectionHeader: { fontSize: 13, fontWeight: 'bold', color: COLORS.gray, marginTop: 30, marginBottom: 12, letterSpacing: 1 },
  // "Similar Items" horizontal scroller: each ItemCard is reused outside its native
  // 2-column grid, so it needs a fixed pixel width here instead of the percentage
  // widths ItemCard uses internally (those only resolve correctly inside a
  // fixed-width grid column, not inside an auto-sized horizontal ScrollView).
  similarItemsSection: { marginTop: 24 },
  similarItemsTitle: { fontSize: 14, fontWeight: 'bold', color: COLORS.black, marginBottom: 12 },
  similarItemWrapper: { marginRight: 12 },
  description: { fontSize: 16, color: COLORS.black, lineHeight: 26, opacity: 0.8 },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    paddingBottom: Platform.OS === 'ios' ? 35 : 20,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: COLORS.lightGray,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 5
  },
  chatButton: {
    flex: 0.8,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 28,
    marginRight: 12,
    flexDirection: 'row'
  },
  chatButtonText: { color: COLORS.primary, fontWeight: 'bold', marginLeft: 8, fontSize: 15 },
  buyButton: {
    flex: 1.2,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.secondary,
    borderRadius: 28
  },
  buyButtonText: { color: COLORS.white, fontSize: 16, fontWeight: 'bold' },
  surveyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 16,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  surveyGridItem: {
    width: '50%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
  },
  surveyGridLabel: {
    fontSize: 13,
    color: COLORS.black,
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif',
  },
  surveyGridLabelDisabled: {
    color: COLORS.gray,
    textDecorationLine: 'line-through',
    opacity: 0.7,
  },
  timelineContainer: {
    backgroundColor: COLORS.white,
    padding: 20,
    borderRadius: 16,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  timelineItem: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  timelineLeftColumn: {
    alignItems: 'center',
    marginRight: 12,
  },
  timelineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    zIndex: 2,
    marginTop: 4,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: COLORS.lightGray,
    marginTop: 4,
    marginBottom: -16,
  },
  timelineContent: {
    flex: 1,
    paddingBottom: 4,
  },
  timelineLabel: {
    fontSize: 14,
    color: COLORS.black,
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif',
  },
  timelineStatus: {
    fontSize: 12,
    color: COLORS.gray,
    marginTop: 2,
  },
  priceOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  priceModalContent: {
    backgroundColor: 'white',
    borderRadius: 20,
    width: '90%',
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  priceModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  priceModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.black,
  },
  priceModalLabel: {
    fontSize: 14,
    color: COLORS.gray,
    marginBottom: 16,
  },
  priceAlertInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#F8FAFC',
    marginBottom: 20,
  },
  priceAlertCurrency: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.black,
    marginRight: 6,
  },
  priceAlertInput: {
    flex: 1,
    fontSize: 16,
    color: COLORS.black,
  },
  priceAlertSubmitBtn: {
    backgroundColor: '#064E3B',
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  priceAlertSubmitBtnText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
  },
  reportListingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    marginTop: 25,
    borderWidth: 1,
    borderColor: '#FEE2E2',
    backgroundColor: '#FEF2F2',
    borderRadius: 14,
  },
  reportListingText: {
    color: COLORS.danger,
    fontSize: 13,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif',
  },
  soldButton: {
    flex: 1.2,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.success,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginRight: 10,
  },
  soldButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif',
  },
  editButton: {
    flex: 1,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginRight: 10,
  },
  editButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif',
  },
  deleteButton: {
    flex: 1,
    height: 50,
    borderRadius: 25,
    borderWidth: 1.5,
    borderColor: COLORS.danger,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  deleteButtonText: {
    color: COLORS.danger,
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif',
  },
  soldBanner: {
    flex: 1.2,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.eco,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginRight: 10,
    borderWidth: 1,
    borderColor: COLORS.success + '30',
  },
  soldBannerText: {
    color: COLORS.success,
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 28,
    resizeMode: 'cover',
  },
  socialProofRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  viewCountBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.lightGray,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  viewCountText: {
    fontSize: 12,
    color: COLORS.gray,
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif',
  },
  flawBox: {
    backgroundColor: '#FFFBEB',
    borderWidth: 1,
    borderColor: '#FDE68A',
    padding: 16,
    borderRadius: 16,
    marginTop: 20,
    marginBottom: 10,
  },
  flawHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  flawTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#B45309',
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif',
  },
  flawText: {
    fontSize: 14,
    color: '#78350F',
    lineHeight: 20,
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif',
  },
  disclosureCard: {
    backgroundColor: COLORS.white,
    padding: 20,
    borderRadius: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
  },
  disclosureHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGray,
    paddingBottom: 12,
    marginBottom: 15,
  },
  disclosureTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  disclosureTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.black,
  },

  gradeBadgeText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: COLORS.success,
  },
  disclosureNotesBox: {
    backgroundColor: COLORS.background,
    padding: 15,
    borderRadius: 12,
    marginBottom: 18,
  },
  disclosureNotesTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: COLORS.gray,
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  disclosureNotesText: {
    fontSize: 14,
    color: COLORS.black,
    lineHeight: 20,
  },
  snapshotContainer: {
    marginTop: 5,
  },
  snapshotSectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.black,
    marginBottom: 12,
  },
  snapshotSplit: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  snapshotColumn: {
    width: '48%',
    backgroundColor: COLORS.background,
    padding: 12,
    borderRadius: 12,
  },
  snapshotColumnHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGray,
    paddingBottom: 6,
    marginBottom: 8,
  },
  snapshotColumnTitle: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  snapshotItemRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  bulletDot: {
    fontSize: 12,
    color: COLORS.success,
    marginRight: 4,
    lineHeight: 18,
  },
  snapshotItemText: {
    fontSize: 12,
    color: COLORS.black,
    flex: 1,
    lineHeight: 18,
  },
  failedText: {
    color: COLORS.danger,
  },
  snapshotEmptyText: {
    fontSize: 11,
    color: COLORS.gray,
    fontStyle: 'italic',
  },
  avatarPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  trustScoreText: {
    fontSize: 11,
    color: COLORS.primary,
    fontWeight: '600',
    marginTop: 2,
  },
});
