import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../../utils/constants';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  scrollContent: { paddingBottom: 100 },
  gradientHeader: { padding: 20, paddingTop: 60, paddingBottom: 30, alignItems: 'center', borderBottomLeftRadius: 24, borderBottomRightRadius: 24 },
  mainContentContainer: { paddingHorizontal: 20, paddingBottom: 30 },
  topActions: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    zIndex: 10
  },
  iconCircle: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255, 255, 255, 0.95)', justifyContent: 'center', alignItems: 'center', marginLeft: 12, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 1 },
  profileSection: { alignItems: 'center', width: '100%', marginTop: 10 },
  avatarContainer: { marginBottom: 15 },
  avatar: { width: 100, height: 100, borderRadius: 50, backgroundColor: COLORS.white, justifyContent: 'center', alignItems: 'center', borderWidth: 3, borderColor: 'rgba(255, 255, 255, 0.2)' },
  avatarImage: { width: '100%', height: '100%', borderRadius: 50, resizeMode: 'cover' },
  avatarText: { fontSize: 40, fontWeight: 'bold', color: COLORS.primary },
  verifiedBadge: { position: 'absolute', bottom: 0, right: 0, backgroundColor: 'white', borderRadius: 12, elevation: 4 },
  userName: { fontSize: 24, fontWeight: 'bold', color: COLORS.white },
  trustBadge: { marginTop: 8, backgroundColor: 'rgba(255, 255, 255, 0.15)', paddingHorizontal: 12, paddingVertical: 4, borderRadius: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  trustText: { fontSize: 13, color: '#A7F3D0', fontWeight: 'bold' },
  chatActionBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.white, paddingHorizontal: 20, paddingVertical: 10, borderRadius: 24, marginTop: 10 },
  chatActionText: { color: COLORS.primary, fontWeight: 'bold', marginLeft: 8 },
  statsRow: { flexDirection: 'row', justifyContent: 'space-between', width: '100%', marginTop: 25 },
  statItem: { alignItems: 'center', flex: 1 },
  statValue: { fontSize: 18, fontWeight: 'bold', color: COLORS.black },
  statLabel: { fontSize: 12, color: COLORS.gray, marginTop: 4 },
  impactCard: { marginTop: 30, backgroundColor: COLORS.primary, width: '100%', borderRadius: 20, padding: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  impactContent: { flexDirection: 'row', alignItems: 'center' },
  impactTextContainer: { marginLeft: 15 },
  impactValue: { fontSize: 18, fontWeight: 'bold', color: COLORS.white },
  impactSub: { fontSize: 12, color: COLORS.white, opacity: 0.8, marginTop: 2 },
  tabSection: { width: '100%', marginTop: 25 },
  tabsScroll: { borderBottomWidth: 1, borderBottomColor: COLORS.lightGray },
  tabs: { flexDirection: 'row', paddingBottom: 10 },
  tabItem: { marginRight: 25 },
  tabContent: { flexDirection: 'row', alignItems: 'center' },
  tab: { fontSize: 15, color: COLORS.gray, fontWeight: 'bold' },
  activeTab: { color: COLORS.primary },
  tabBadge: { backgroundColor: COLORS.danger, borderRadius: 10, minWidth: 18, height: 18, justifyContent: 'center', alignItems: 'center', marginLeft: 6 },
  tabBadgeText: { color: 'white', fontSize: 10, fontWeight: 'bold' },
  columnWrapper: { justifyContent: 'space-between', paddingHorizontal: 20 },
  emptyState: { width: '100%', alignItems: 'center', marginTop: 30 },
  emptyText: { color: COLORS.gray },
  reviewCard: { backgroundColor: COLORS.white, marginHorizontal: 20, marginBottom: 12, padding: 16, borderRadius: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  reviewHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  reviewerName: { fontWeight: 'bold', fontSize: 15, color: COLORS.black },
  ratingRow: { flexDirection: 'row' },
  reviewComment: { fontSize: 14, color: COLORS.black, opacity: 0.8, lineHeight: 20 },
  reviewDate: { fontSize: 11, color: COLORS.gray, marginTop: 10 },
  transactionCard: { backgroundColor: COLORS.white, marginHorizontal: 20, marginBottom: 12, padding: 16, borderRadius: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  transactionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  transactionMeta: { flex: 1, marginLeft: 12 },
  transactionTitle: { fontSize: 16, fontWeight: 'bold', color: COLORS.black },
  transactionSeller: { fontSize: 12, color: COLORS.gray, marginTop: 2 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  statusText: { fontSize: 10, fontWeight: 'bold' },
  transactionFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: COLORS.lightGray, paddingTop: 12 },
  transactionPrice: { fontSize: 16, fontWeight: 'bold', color: COLORS.primary },
  transactionDate: { fontSize: 12, color: COLORS.gray },
  transactionImage: { width: 44, height: 44, borderRadius: 8, marginRight: 12 },
  completeBtn: { backgroundColor: COLORS.primary, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10 },
  completeBtnText: { color: 'white', fontSize: 12, fontWeight: 'bold' },
  reviewBtn: { backgroundColor: COLORS.warning, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10 },
  reviewBtnText: { color: COLORS.black, fontSize: 12, fontWeight: 'bold' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 20 },
  modalContent: { backgroundColor: 'white', borderRadius: 20, padding: 25 },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.black },
  modalSub: { fontSize: 14, color: COLORS.gray, marginTop: 5, marginBottom: 20 },
  reportInput: { backgroundColor: COLORS.lightGray, borderRadius: 12, padding: 15, fontSize: 15, height: 100, textAlignVertical: 'top' },
  modalActions: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 20 },
  reportSubmitBtn: { backgroundColor: COLORS.danger, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 12, marginLeft: 10 },
  reportSubmitText: { color: 'white', fontWeight: 'bold' },
  cancelBtn: { paddingHorizontal: 20, paddingVertical: 12, borderRadius: 12, justifyContent: 'center' },
  cancelText: { color: COLORS.gray, fontWeight: 'bold' },

  walletCard: { marginTop: 20, backgroundColor: COLORS.white, width: '100%', borderRadius: 20, padding: 20, borderWidth: 1, borderColor: COLORS.lightGray, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  walletHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  walletTitle: { fontSize: 15, fontWeight: 'bold', color: COLORS.primary },
  walletSub: { fontSize: 11, color: COLORS.gray, opacity: 0.8 },
  topupBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.secondary, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 24 },
  topupText: { color: 'white', fontSize: 11, fontWeight: 'bold' },
  walletBalance: { fontSize: 26, fontWeight: 'bold', color: COLORS.primary },
  amountInputContainer: { flexDirection: 'row', alignItems: 'center', borderBottomWidth: 2, borderBottomColor: COLORS.primary, marginVertical: 15, paddingBottom: 5 },
  currencyPrefix: { fontSize: 20, fontWeight: 'bold', color: COLORS.black, marginRight: 5 },
  amountInput: { flex: 1, fontSize: 24, fontWeight: 'bold', color: COLORS.black, padding: 0 },
  quickAmounts: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20, width: '100%' },
  quickAmountBtn: { backgroundColor: COLORS.lightGray, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8 },
  quickAmountText: { fontSize: 12, fontWeight: 'bold', color: COLORS.black },
  walletSubmitBtn: { backgroundColor: COLORS.secondary, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 12, marginLeft: 10, flexDirection: 'row', alignItems: 'center' },
  walletSubmitText: { color: 'white', fontWeight: 'bold' },

  trustModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  trustHeaderTitleRow: { flexDirection: 'row', alignItems: 'center' },
  modalCloseBtn: { padding: 4 },
  trustOverallContainer: { backgroundColor: COLORS.eco, borderRadius: 12, padding: 15, marginBottom: 20, borderWidth: 1, borderColor: COLORS.lightGray },
  trustOverallLabel: { fontSize: 12, color: COLORS.success, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5 },
  trustOverallValueRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginTop: 4 },
  trustOverallValue: { fontSize: 28, fontWeight: 'bold', color: COLORS.primary },
  trustOverallGrade: { fontSize: 16, fontWeight: 'bold', color: COLORS.success },
  trustBreakdownScroll: { maxHeight: 350 },
  abiSection: { marginBottom: 20 },
  abiHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 6 },
  abiName: { fontSize: 16, fontWeight: 'bold', color: COLORS.black },
  abiWeight: { fontSize: 12, color: COLORS.gray },
  abiScore: { fontSize: 15, fontWeight: 'bold', color: COLORS.black },
  progressBarTrack: { height: 8, backgroundColor: COLORS.lightGray, borderRadius: 4, overflow: 'hidden', marginBottom: 6 },
  progressBarFill: { height: '100%', borderRadius: 4 },
  abiDescription: { fontSize: 12, color: COLORS.gray, lineHeight: 16 },
  trustInfoCard: { flexDirection: 'row', backgroundColor: COLORS.eco, borderRadius: 12, padding: 12, marginTop: 10, borderWidth: 1, borderColor: COLORS.lightGray, alignItems: 'flex-start' },
  trustInfoText: { flex: 1, fontSize: 11, color: COLORS.success, lineHeight: 16 },

  ledgerCard: { backgroundColor: COLORS.white, marginHorizontal: 20, marginBottom: 10, padding: 16, borderRadius: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  ledgerHeader: { flexDirection: 'row', alignItems: 'center' },
  ledgerIconContainer: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  ledgerMeta: { flex: 1 },
  ledgerTitle: { fontSize: 14, fontWeight: 'bold', color: COLORS.black },
  ledgerDate: { fontSize: 11, color: COLORS.gray, marginTop: 4 },
  ledgerAmount: { fontSize: 15, fontWeight: 'bold' },

  receiptBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.eco, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 24, borderWidth: 1, borderColor: COLORS.lightGray },
  receiptBtnText: { color: COLORS.success, fontSize: 12, fontWeight: 'bold' },
  receiptPaper: { backgroundColor: COLORS.white, borderRadius: 20, padding: 25, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 10, elevation: 5, width: '100%', maxWidth: 340, alignSelf: 'center' },
  receiptMerchant: { fontSize: 13, fontWeight: 'bold', color: COLORS.black, letterSpacing: 1, textAlign: 'center' },
  receiptMerchantSub: { fontSize: 10, color: COLORS.gray, marginTop: 2, textAlign: 'center' },
  receiptStampContainer: { position: 'absolute', top: 20, right: 20, zIndex: 10 },
  receiptStamp: { borderWidth: 2, borderColor: COLORS.success, borderRadius: 4, paddingHorizontal: 6, paddingVertical: 2, transform: [{ rotate: '-15deg' }] },
  receiptStampText: { color: COLORS.success, fontSize: 11, fontWeight: 'bold', letterSpacing: 1 },
  receiptDashedLine: { height: 1, borderStyle: 'dashed', borderWidth: 1, borderColor: COLORS.lightGray, borderRadius: 1, marginVertical: 15, overflow: 'hidden' },
  receiptDetails: { marginVertical: 5 },
  receiptRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  receiptLabel: { fontSize: 12, color: COLORS.gray },
  receiptValue: { fontSize: 12, fontWeight: '600', color: COLORS.black },
  receiptItems: { marginVertical: 5 },
  receiptItemRow: { flexDirection: 'row', justifyContent: 'space-between' },
  receiptItemName: { fontSize: 14, fontWeight: 'bold', color: COLORS.black, flex: 1 },
  receiptItemPrice: { fontSize: 14, fontWeight: 'bold', color: COLORS.black, marginLeft: 10 },
  receiptPricing: { marginVertical: 5 },
  receiptPriceRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  receiptPriceLabel: { fontSize: 12, color: COLORS.gray },
  receiptPriceVal: { fontSize: 12, color: COLORS.black, opacity: 0.8 },
  receiptTotalLabel: { fontSize: 14, fontWeight: 'bold', color: COLORS.black },
  receiptTotalVal: { fontSize: 16, fontWeight: 'bold', color: COLORS.primary },
  receiptFooter: { alignItems: 'center', marginTop: 5, marginBottom: 15 },
  receiptFooterCode: { fontSize: 9, color: COLORS.gray, letterSpacing: 2, marginTop: 2 },
  receiptEcoBanner: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.eco, borderRadius: 8, padding: 8, marginTop: 12, borderWidth: 1, borderColor: COLORS.lightGray },
  receiptEcoText: { flex: 1, fontSize: 10, color: COLORS.success, lineHeight: 14, fontWeight: '500' },
  receiptCloseBtn: { backgroundColor: COLORS.primary, borderRadius: 24, paddingVertical: 12, alignItems: 'center', width: '100%', marginTop: 5 },
  receiptCloseBtnText: { color: 'white', fontWeight: 'bold', fontSize: 14 },

  bioText: { color: 'rgba(255, 255, 255, 0.95)', fontSize: 14, textAlign: 'center', marginTop: 10, paddingHorizontal: 30, fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'PlusJakartaSans-Regular', lineHeight: 20 },
  bioPlaceholderText: { color: 'rgba(255, 255, 255, 0.5)', fontSize: 12, textAlign: 'center', marginTop: 10, paddingHorizontal: 30, fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'PlusJakartaSans-Regular', fontStyle: 'italic' },
  infoRowInline: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 12, width: '100%', flexWrap: 'wrap' },
  infoBadgeInline: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255, 255, 255, 0.15)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, marginBottom: 5 },
  infoBadgeTextInline: { color: 'rgba(255, 255, 255, 0.9)', fontSize: 11, fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'PlusJakartaSans-SemiBold' },
  fieldLabel: { fontSize: 13, color: COLORS.gray, fontWeight: 'bold', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 },
  singleLineInput: { backgroundColor: COLORS.lightGray, borderRadius: 12, paddingHorizontal: 15, paddingVertical: 10, fontSize: 15, color: COLORS.black, fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'PlusJakartaSans-Regular' },
  bioInput: { backgroundColor: COLORS.lightGray, borderRadius: 12, padding: 15, fontSize: 15, color: COLORS.black, height: 80, textAlignVertical: 'top', fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'PlusJakartaSans-Regular' },

  reviewsSummaryBanner: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    marginTop: 15,
    marginBottom: 5,
    borderWidth: 1,
    borderColor: COLORS.lightGray,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    alignItems: 'center',
  },
  summaryLeft: {
    flex: 0.45,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: COLORS.lightGray,
    paddingRight: 10,
  },
  summaryAvgRating: {
    fontSize: 36,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  summaryStarsRow: {
    flexDirection: 'row',
    marginVertical: 4,
  },
  summaryTotalCount: {
    fontSize: 11,
    color: COLORS.gray,
    fontWeight: '600',
  },
  summaryRight: {
    flex: 0.55,
    paddingLeft: 15,
    justifyContent: 'center',
  },
  breakdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  breakdownStarsText: {
    fontSize: 10,
    color: COLORS.gray,
    width: 18,
    textAlign: 'right',
    marginRight: 6,
    fontWeight: '600',
  },
  breakdownProgressTrack: {
    flex: 1,
    height: 6,
    backgroundColor: COLORS.lightGray,
    borderRadius: 3,
    overflow: 'hidden',
  },
  breakdownProgressFill: {
    height: '100%',
    backgroundColor: '#FBBF24',
    borderRadius: 3,
  },
  breakdownCountText: {
    fontSize: 10,
    color: COLORS.gray,
    width: 16,
    textAlign: 'left',
    marginLeft: 6,
    fontWeight: '600',
  },
  requestVerifyBtn: {
    marginTop: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.20)',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  requestVerifyBtnText: {
    fontSize: 12,
    color: '#A7F3D0',
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif',
  },
  createBundleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 20,
    marginVertical: 10,
    paddingVertical: 12,
    borderRadius: 12,
  },
  createBundleBtnText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
  },
  bundlesSection: {
    marginHorizontal: 20,
    marginVertical: 10,
  },
  bundlesTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  bundlesScroll: {
    paddingRight: 20,
  },
  bundleCard: {
    width: 200,
    borderWidth: 1,
    borderRadius: 16,
    padding: 12,
    marginRight: 12,
  },
  bundleName: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  bundlePrice: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#10B981',
    marginBottom: 4,
  },
  bundleMeta: {
    fontSize: 12,
    marginBottom: 8,
  },
  bundleImagesRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  bundleMiniImage: {
    width: 32,
    height: 32,
    borderRadius: 6,
    marginRight: 4,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  deleteBundleBtn: {
    backgroundColor: '#EF444415',
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: 'center',
  },
  deleteBundleText: {
    color: '#EF4444',
    fontSize: 11,
    fontWeight: 'bold',
  },
  buyBundleBtn: {
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: 'center',
  },
  buyBundleText: {
    color: 'white',
    fontSize: 11,
    fontWeight: 'bold',
  },
  bundleModalContent: {
    backgroundColor: 'white',
    borderRadius: 20,
    width: '90%',
    maxHeight: '80%',
    padding: 20,
  },
  bundleFormScroll: {
    marginVertical: 15,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: 'bold',
    color: COLORS.black,
    marginBottom: 6,
  },
  bundleInput: {
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
    fontSize: 14,
  },
  bundleItemSelect: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    marginBottom: 8,
  },
  bundleItemSelectActive: {
    borderColor: '#064E3B',
    backgroundColor: '#064E3B05',
  },
  bundleItemThumbnail: {
    width: 40,
    height: 40,
    borderRadius: 8,
  },
  bundleItemName: {
    fontSize: 13,
    fontWeight: 'bold',
  },
  bundleItemPrice: {
    fontSize: 12,
    color: COLORS.gray,
  },
  createBundleSubmitBtn: {
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  createBundleSubmitText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
  },
  noItemsText: {
    fontSize: 13,
    color: COLORS.gray,
    textAlign: 'center',
    marginVertical: 20,
  },
  stripeBalanceCard: {
    marginHorizontal: 16,
    marginTop: -20,
    marginBottom: 20,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  stripeBalanceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  stripeBalanceTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  stripeBalanceAmounts: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  stripeBalanceColumn: {
    flex: 1,
    alignItems: 'center',
  },
  stripeBalanceLabel: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 4,
  },
  stripeBalanceValue: {
    fontWeight: 'bold',
    fontSize: 20,
  },
  stripeBalanceDivider: {
    width: 1,
    height: '100%',
    backgroundColor: '#D1D5DB',
    marginHorizontal: 16,
  },
  stripeDashboardBtn: {
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
  },
  stripeDashboardText: {
    fontWeight: 'bold',
    fontSize: 14,
    color: 'white',
  },
  sortContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 4,
    marginBottom: 12,
  },
  sortTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: COLORS.gray,
    marginRight: 8,
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif',
  },
  sortList: {
    alignItems: 'center',
    paddingRight: 20,
  },
  sortChip: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 15,
    marginRight: 8,
    backgroundColor: COLORS.lightGray,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  activeSortChip: {
    backgroundColor: COLORS.primary + '10',
    borderColor: COLORS.primary + '30',
  },
  sortChipText: {
    fontSize: 12,
    color: COLORS.gray,
    fontFamily: Platform.OS === 'ios' ? 'Plus Jakarta Sans' : 'sans-serif',
  },
  activeSortChipText: {
    color: COLORS.primary,
    fontWeight: 'bold',
  },
});
