import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../../utils/constants';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  header: { paddingTop: 60, paddingBottom: 15, paddingHorizontal: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: COLORS.background },
  headerTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.black,
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif'
  },
  stepBadge: { backgroundColor: COLORS.lightGray, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 },
  stepBadgeText: { fontSize: 12, fontWeight: 'bold', color: COLORS.gray },
  progressBar: { height: 4, backgroundColor: COLORS.lightGray, width: '100%' },
  progressFill: { height: '100%', backgroundColor: COLORS.primary },
  content: { padding: 20, paddingBottom: 130 },

  section: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  sectionLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.black,
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif'
  },
  sectionSub: { fontSize: 12, color: COLORS.gray },
  photoList: { flexDirection: 'row', marginBottom: 25 },
  addPhotoBox: {
    width: 100,
    height: 100,
    borderRadius: 16,
    borderStyle: 'dashed',
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1
  },
  addPhotoText: { fontSize: 10, color: COLORS.primary, fontWeight: 'bold', marginTop: 4 },
  photoItem: { width: 100, height: 100, marginLeft: 10, borderRadius: 16, overflow: 'hidden' },
  thumbnail: { width: '100%', height: '100%' },
  removePhoto: { position: 'absolute', top: 5, right: 5, zIndex: 5 },
  label: { fontSize: 14, fontWeight: '600', color: COLORS.black, marginBottom: 8, marginTop: 10 },
  input: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    fontSize: 16,
    color: COLORS.black,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1
  },
  categoryPicker: { marginBottom: 20 },
  catChip: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 24,
    backgroundColor: COLORS.white,
    marginRight: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1
  },
  activeCatChip: { backgroundColor: COLORS.primary },
  catChipText: { color: COLORS.gray, fontWeight: '600' },
  activeCatChipText: { color: COLORS.white },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    paddingHorizontal: 16,
    height: 56,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1
  },
  currency: { fontSize: 18, fontWeight: 'bold', color: COLORS.gray, marginRight: 8 },
  priceInput: { flex: 1, fontSize: 18, fontWeight: 'bold', color: COLORS.black },
  toggleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 30 },
  toggleLabel: { fontSize: 16, fontWeight: 'bold', color: COLORS.black },
  toggleSub: { fontSize: 12, color: COLORS.gray },
  switch: { width: 50, height: 28, borderRadius: 14, backgroundColor: COLORS.lightGray, padding: 2, borderWidth: 1, borderColor: '#E5E7EB' },
  switchOn: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  switchKnob: { width: 22, height: 22, borderRadius: 11, backgroundColor: COLORS.white, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.2, shadowRadius: 1 },
  switchKnobOn: { alignSelf: 'flex-end' },
  nextButton: { backgroundColor: COLORS.primary, height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center', marginTop: 30, marginBottom: 15 },
  disabledButton: { backgroundColor: COLORS.gray },

  nextButtonText: { color: COLORS.white, fontSize: 16, fontWeight: 'bold' },
  stepHeader: { marginBottom: 25 },
  stepTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: COLORS.black,
    fontFamily: Platform.OS === 'ios' ? 'Playfair Display' : 'serif'
  },
  stepSub: { fontSize: 14, color: COLORS.gray, marginTop: 8 },
  surveyCard: {
    flexDirection: 'row',
    padding: 16,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    marginBottom: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1.5,
    borderColor: 'transparent'
  },
  activeSurveyCard: { borderColor: COLORS.primary, backgroundColor: COLORS.eco },
  surveyInfo: { flex: 1 },
  surveyLabel: { fontSize: 16, fontWeight: 'bold', color: COLORS.black },
  surveyDesc: { fontSize: 12, color: COLORS.gray, marginTop: 2 },
  surveyCheckbox: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: COLORS.lightGray, justifyContent: 'center', alignItems: 'center' },
  surveyCheckboxChecked: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  gradePreview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    padding: 18,
    borderRadius: 16,
    marginVertical: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1
  },
  previewLabel: { fontSize: 14, fontWeight: '600', color: COLORS.black },
  previewBadge: { backgroundColor: COLORS.primary, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16, flexDirection: 'row', alignItems: 'center' },
  previewGrade: { color: 'white', fontWeight: 'bold', fontSize: 12 },
  submitButton: { backgroundColor: COLORS.secondary, height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center', marginTop: 30, marginBottom: 10 },
  submitButtonText: { color: COLORS.white, fontSize: 18, fontWeight: 'bold' },
  backLink: { marginTop: 20, alignItems: 'center' },
  backLinkText: { color: COLORS.gray, textDecorationLine: 'underline' },
  aiButton: { backgroundColor: COLORS.secondary, height: 46, borderRadius: 23, justifyContent: 'center', alignItems: 'center', marginBottom: 20, flexDirection: 'row' },
  aiButtonText: { color: COLORS.white, fontSize: 14, fontWeight: 'bold' },
  aiReportCard: {
    backgroundColor: COLORS.eco,
    borderRadius: 16,
    padding: 18,
    marginVertical: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1
  },
  aiReportHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  aiReportTitle: { fontSize: 15, fontWeight: 'bold', color: COLORS.primary },
  aiReportText: { fontSize: 13, color: COLORS.gray, lineHeight: 18, marginBottom: 8 },
  aiReportPrice: { fontSize: 24, fontWeight: '800', color: COLORS.primary, marginVertical: 6 },
  aiReportWarning: { fontSize: 12, fontWeight: '600', lineHeight: 16 }
});

export default styles;
