from rest_framework import viewsets, permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from django.db.models import Prefetch
from rest_framework.decorators import action
from .models import Category, Profile, Item, Transaction, Message, ScamReport, Notification, Review
from .serializers import (
    CategorySerializer, ProfileSerializer, ItemSerializer,
    TransactionSerializer, MessageSerializer, ScamReportSerializer,
    NotificationSerializer, ChangePasswordSerializer,
    ReviewSerializer, RegisterSerializer, UserSerializer
)


class RegisterView(APIView):
    """Handles new user registration and returns an auth token."""
    permission_classes = [permissions.AllowAny]

    def post(self, request):
        serializer = RegisterSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.save()
            token, created = Token.objects.get_or_create(user=user)
            return Response({
                'token': token.key,
                'user': UserSerializer(user).data
            }, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ChangePasswordView(APIView):
    """Allows authenticated users to change their password."""
    permission_classes = [permissions.AllowAny] # In prod: IsAuthenticated

    def post(self, request):
        serializer = ChangePasswordSerializer(data=request.data)
        if serializer.is_valid():
            user = request.user
            if user.is_anonymous:
                from django.contrib.auth.models import User
                user = User.objects.first() # Dev hack
            
            if not user.check_password(serializer.data.get("old_password")):
                return Response({"old_password": ["Wrong password."]}, status=status.HTTP_400_BAD_REQUEST)
            
            user.set_password(serializer.data.get("new_password"))
            user.save()
            return Response({"status": "Password updated successfully"}, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class LoginView(ObtainAuthToken):
    """Authenticates user and returns token plus basic user info."""
    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data, context={'request': request})
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token, created = Token.objects.get_or_create(user=user)
        return Response({
            'token': token.key,
            'user': UserSerializer(user).data
        })


class NotificationViewSet(viewsets.ReadOnlyModelViewSet):
    """User notifications. Read-only as they are generated by backend signals."""
    serializer_class = NotificationSerializer
    permission_classes = [permissions.AllowAny]

    def get_queryset(self):
        user = self.request.user
        if user.is_anonymous:
            from django.contrib.auth.models import User
            user = User.objects.first()
        return Notification.objects.filter(user=user)

    @action(detail=True, methods=['post'])
    def mark_as_read(self, request, pk=None):
        notification = self.get_object()
        notification.is_read = True
        notification.save()
        return Response({'status': 'notification marked as read'})


class CategoryViewSet(viewsets.ModelViewSet):
    """CRUD operations for categories."""
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [permissions.AllowAny]


class ProfileViewSet(viewsets.ModelViewSet):
    """CRUD operations for user profiles. Optimized queries using select_related."""
    queryset = Profile.objects.select_related('user').all()
    serializer_class = ProfileSerializer
    permission_classes = [permissions.AllowAny]


class ItemViewSet(viewsets.ModelViewSet):
    """CRUD operations for items. Uses select_related and prefetch_related for optimal performance."""
    # select_related for 1:1 and ForeignKeys, prefetch_related for Many-to-Many and reverse ForeignKeys
    queryset = Item.objects.select_related('seller', 'category').prefetch_related('images').all()
    serializer_class = ItemSerializer
    permission_classes = [permissions.AllowAny]
    
    # Advanced Filtering, Searching, and Ordering
    filterset_fields = ['category', 'calculated_grade', 'is_sold', 'price']
    search_fields = ['name', 'description']
    ordering_fields = ['price', 'created_at']

    def perform_create(self, serializer):
        # Auto-assign the currently authenticated user as the seller
        # Fallback to the first user if anonymous (for initial development ease)
        from django.contrib.auth.models import User
        user = self.request.user
        if user.is_anonymous:
            user = User.objects.first() # Temporary dev hack since Auth isn't enforced yet
        serializer.save(seller=user)


class TransactionViewSet(viewsets.ModelViewSet):
    """CRUD operations for transactions. Automatically assigns buyer/seller and price."""
    queryset = Transaction.objects.select_related('item', 'buyer', 'seller').all()
    serializer_class = TransactionSerializer
    permission_classes = [permissions.AllowAny] # Change to IsAuthenticated later

    def perform_create(self, serializer):
        item = serializer.validated_data['item']
        user = self.request.user
        if user.is_anonymous:
            from django.contrib.auth.models import User
            user = User.objects.first()
            
        serializer.save(
            buyer=user,
            seller=item.seller,
            final_price=item.price
        )


class MessageViewSet(viewsets.ModelViewSet):
    """CRUD operations for in-app messages. Optimized and restricted to user's own chats."""
    serializer_class = MessageSerializer
    permission_classes = [permissions.AllowAny] # Change to IsAuthenticated later

    def get_queryset(self):
        user = self.request.user
        if user.is_anonymous:
            from django.contrib.auth.models import User
            user = User.objects.first()
        
        # Only see messages where user is sender or receiver
        from django.db.models import Q
        return Message.objects.filter(Q(sender=user) | Q(receiver=user)).select_related('sender', 'receiver', 'item')

    def perform_create(self, serializer):
        user = self.request.user
        if user.is_anonymous:
            from django.contrib.auth.models import User
            user = User.objects.first()
        serializer.save(sender=user)


class ScamReportViewSet(viewsets.ModelViewSet):
    """CRUD operations for scam reports. Users can create reports and see their own filed reports."""
    serializer_class = ScamReportSerializer
    permission_classes = [permissions.AllowAny]

    def get_queryset(self):
        user = self.request.user
        if user.is_anonymous:
            from django.contrib.auth.models import User
            user = User.objects.first()
        
        # Regular users can only see reports they filed
        # Admins can see everything (handled by Django permissions eventually)
        return ScamReport.objects.filter(reporter=user).select_related('reporter', 'reported_user', 'item')

    def perform_create(self, serializer):
        user = self.request.user
        if user.is_anonymous:
            from django.contrib.auth.models import User
            user = User.objects.first()
        serializer.save(reporter=user)


class ReviewViewSet(viewsets.ModelViewSet):
    """CRUD operations for reviews."""
    queryset = Review.objects.select_related('item', 'reviewer', 'seller').all()
    serializer_class = ReviewSerializer
    permission_classes = [permissions.AllowAny]

    def perform_create(self, serializer):
        # Auto-assign the currently authenticated user as the reviewer
        from django.contrib.auth.models import User
        user = self.request.user
        if user.is_anonymous:
            user = User.objects.first()
        serializer.save(reviewer=user)
